services:
  myshop-app:
    image: ${APP_IMAGE}
    container_name: myshop-app
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
    ports:
      - "8080:8080"
        

