name: Build & Push (Docker Hub)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn -B clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: meta
        run: |
          APP_VER=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "APP_VER=$APP_VER" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myshop:${{ steps.meta.outputs.APP_VER }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/myshop:latest .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myshop:${{ steps.meta.outputs.APP_VER }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myshop:latest
